import type { Icon } from "@phosphor-icons/react";
import {
  AirplaneIcon,
  AtomIcon,
  BicycleIcon,
  BookOpenIcon,
  BrainIcon,
  BriefcaseIcon,
  BuildingsIcon,
  CameraIcon,
  CatIcon,
  ChatCircleIcon,
  CodeIcon,
  CoffeeIcon,
  CurrencyDollarIcon,
  DogIcon,
  FlagIcon,
  FlaskIcon,
  FlowerIcon,
  GameControllerIcon,
  GearIcon,
  GlobeIcon,
  GraduationCapIcon,
  HeartIcon,
  HouseIcon,
  LaptopIcon,
  LeafIcon,
  LightbulbIcon,
  LightningIcon,
  MegaphoneIcon,
  MoonIcon,
  MountainsIcon,
  MusicNoteIcon,
  PaletteIcon,
  PencilSimpleIcon,
  RocketIcon,
  ShieldCheckIcon,
  ShoppingCartIcon,
  SmileyIcon,
  SparkleIcon,
  StarIcon,
  SunIcon,
  TrophyIcon,
  UsersIcon,
  WrenchIcon,
} from "@phosphor-icons/react";

export const PROFILE_ICON_MAP: Record<string, Icon> = {
  House: HouseIcon,
  ChatCircle: ChatCircleIcon,
  Star: StarIcon,
  Heart: HeartIcon,
  Flag: FlagIcon,
  Lightning: LightningIcon,
  Gear: GearIcon,
  Lightbulb: LightbulbIcon,
  Briefcase: BriefcaseIcon,
  Buildings: BuildingsIcon,
  GraduationCap: GraduationCapIcon,
  Code: CodeIcon,
  BookOpen: BookOpenIcon,
  PencilSimple: PencilSimpleIcon,
  Palette: PaletteIcon,
  Flask: FlaskIcon,
  GameController: GameControllerIcon,
  MusicNote: MusicNoteIcon,
  Camera: CameraIcon,
  Airplane: AirplaneIcon,
  Bicycle: BicycleIcon,
  Coffee: CoffeeIcon,
  Leaf: LeafIcon,
  Globe: GlobeIcon,
  Rocket: RocketIcon,
  ShieldCheck: ShieldCheckIcon,
  Wrench: WrenchIcon,
  Sparkle: SparkleIcon,
  Atom: AtomIcon,
  Brain: BrainIcon,
  Trophy: TrophyIcon,
  Smiley: SmileyIcon,
  Dog: DogIcon,
  Cat: CatIcon,
  Sun: SunIcon,
  Moon: MoonIcon,
  Mountains: MountainsIcon,
  Flower: FlowerIcon,
  ShoppingCart: ShoppingCartIcon,
  CurrencyDollar: CurrencyDollarIcon,
  Users: UsersIcon,
  Laptop: LaptopIcon,
  Megaphone: MegaphoneIcon,
};

export const PROFILE_ICON_NAMES = Object.keys(PROFILE_ICON_MAP);

export function getProfileIconComponent(name: string): Icon | undefined {
  return PROFILE_ICON_MAP[name];
}
