export const ROUTES = {
  HOME: "/",
  AUTH: "/auth",
  CHAT: "/chat",
  CHAT_CONVERSATION: (conversationId: string) => `/chat/${conversationId}`,
  PRIVATE_CHAT: "/private",
  SHARE: (shareId: string) => `/share/${shareId}`,
  SETTINGS: {
    ROOT: "/settings",
    API_KEYS: "/settings/api-keys",
    MODELS: "/settings/models",
    TEXT_MODELS: "/settings/models/text",
    IMAGE_MODELS: "/settings/models/image",
    TTS_MODELS: "/settings/models/tts",
    PERSONAS: "/settings/personas",
    PERSONAS_NEW: "/settings/personas/new",
    PERSONAS_EDIT: (id: string) => `/settings/personas/${id}/edit`,
    SHARED_CONVERSATIONS: "/settings/shared-conversations",
    ARCHIVED_CONVERSATIONS: "/settings/archived-conversations",
    CHAT_HISTORY: "/settings/chat-history",
    ATTACHMENTS: "/settings/attachments",
    MEMORY: "/settings/memory",
    GENERAL: "/settings/general",
  },
  FAVORITES: "/chat/favorites",
  NOT_FOUND: "/404",
} as const;
