language: en-US

reviews:
  high_level_summary: false
  estimate_code_review_effort: false
  assess_linked_issues: false
  profile: chill
  path_instructions:
    - path: "**/*.{ts,tsx,js,jsx}"
      instructions: "Focus on security vulnerabilities, bugs, and architectural concerns. Skip style suggestions, formatting, naming conventions, and optional chaining suggestions as Biome handles these. Do not suggest code style improvements."

path_filters:
  - "!**/*.test.*"
  - "!**/*.spec.*"
  - "!convex/_generated/**"
  - "!build/**"
  - "!dist/**"
  - "!node_modules/**"

disable:
  - format
  - documentation
  - test_coverage

