# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US

reviews:
  sequence_diagrams: false
  poem: false
  in_progress_fortune: false
  related_prs: false
  estimate_code_review_effort: false
  profile: chill
  path_filters:
    - "!**/*.test.*"
    - "!**/*.spec.*"
    - "!convex/_generated/**"
    - "!build/**"
    - "!dist/**"
    - "!node_modules/**"
  path_instructions:
    - path: "**/*.{ts,tsx,js,jsx}"
      instructions: >
        Focus only on security vulnerabilities, bugs, and architectural concerns.
        Skip style, formatting, naming, and cosmetic suggestions handled by Biome.
        Do not suggest code style improvements.
